// Question bank for department-based onboarding.
// Each department maps to a module; each question becomes a quest (row in `questions` table).

export const DEPT_MODULE_META = {
  IT:         { name: "IT",         purpose: "Technology controls and data protection for IT systems" },
  HR:         { name: "HR",         purpose: "Human resources data privacy and compliance controls" },
  Finance:    { name: "Finance",    purpose: "Financial data protection and compliance controls" },
  Legal:      { name: "Legal",      purpose: "Legal data governance and compliance controls" },
  Operations: { name: "Operations", purpose: "Operational data privacy and security controls" },
  Marketing:  { name: "Marketing",  purpose: "Marketing data usage, consent and privacy controls" },
};

export const DEPT_QUESTIONS = {
  IT: [
    { cat: "Data Discovery & Classification",   text: "Required for Identifying & Mapping Personal Data",              priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Consent & Notice Management",        text: "Required for Managing Notice & Consent",                        priority: "High",   tags: "DPDPA,Legal" },
    { cat: "Data Principal Requests",            text: "Required for Managing Data Principal Requests",                 priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Data Retention & Deletion",          text: "Required for Managing Data Retention & Deletion",               priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Personal Data Security",             text: "Required for Securing Personal Data",                           priority: "Critical", tags: "DPDPA,Technical" },
    { cat: "Device Security",                    text: "Required for Securing Devices Handling Personal Data",          priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Application & API Security",         text: "Required for Securing Applications & APIs Collecting Personal Data", priority: "High", tags: "DPDPA,Technical" },
    { cat: "Cloud & Infrastructure Security",    text: "Required for Securing Cloud & Infrastructure",                  priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Data Sharing & Leakage Control",     text: "Required for Controlling Data Sharing & Leakage",              priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Vendor & Processor Management",      text: "Required for Managing Third Parties & Data Processors",        priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Access & Identity Management",       text: "Required for Managing Access & Delegated Authority",           priority: "Critical", tags: "DPDPA,Technical" },
    { cat: "Breach Detection",                   text: "Required for Detecting a Personal Data Breach",                 priority: "Critical", tags: "DPDPA,Technical" },
    { cat: "Incident Response",                  text: "Required for Responding to a Personal Data Breach",            priority: "Critical", tags: "DPDPA,Organisational" },
    { cat: "Recovery & Backup",                  text: "Required for Recovery After an Incident",                       priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Continuous Compliance Monitoring",   text: "Required for Monitoring Compliance Continuously",               priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Evidence & Audit Trail",             text: "Required for Maintaining Evidence & Audit Trail",               priority: "High",   tags: "DPDPA,Organisational" },
  ],
  HR: [
    { cat: "Employee Data & Consent",    text: "Do you maintain a lawful basis for processing employee personal data?",                                       priority: "High",   tags: "DPDPA,GDPR,Legal" },
    { cat: "Employee Data & Consent",    text: "Do candidates and employees receive a clear privacy notice explaining what data is collected and how it is used?", priority: "High", tags: "DPDPA,GDPR,Legal" },
    { cat: "Employee Data & Consent",    text: "Do employees have a mechanism to access, correct, or request deletion of their personal data held by HR?",      priority: "High",   tags: "DPDPA,GDPR,Organisational" },
    { cat: "Sensitive Data Protection",  text: "Are sensitive employee data categories (health records, biometrics, union membership) identified and afforded heightened protection?", priority: "Critical", tags: "DPDPA,GDPR,Technical" },
    { cat: "Sensitive Data Protection",  text: "Is access to HR Information Systems (HRMS / payroll) restricted to authorised HR and payroll staff only?",       priority: "Critical", tags: "DPDPA,Technical" },
    { cat: "Sensitive Data Protection",  text: "Is payroll and salary data encrypted both at rest and in transit?",                                               priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Data Retention",             text: "Do you have defined retention schedules for candidate data and delete it on expiry?",                             priority: "High",   tags: "DPDPA,GDPR,Organisational" },
    { cat: "Data Retention",             text: "Is ex-employee data securely archived and deleted after the legally required retention period?",                  priority: "High",   tags: "DPDPA,Legal" },
    { cat: "Vendor & Third-Party",       text: "Do third-party HR vendors have signed Data Processing Agreements?",                                               priority: "High",   tags: "DPDPA,GDPR,Legal" },
    { cat: "Vendor & Third-Party",       text: "Are background checks conducted through vetted providers contractually bound to data protection standards?",       priority: "Medium", tags: "DPDPA,Organisational" },
    { cat: "Audit & Access Control",     text: "Are HR records stored in controlled systems with audit trails?",                                                   priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Training & Awareness",       text: "Are HR staff trained annually on data privacy obligations, including handling of sensitive personal data?",         priority: "Medium", tags: "DPDPA,Organisational" },
  ],
  Finance: [
    { cat: "Data Inventory & Classification", text: "Do you maintain a data inventory of all personal and financial data processed by Finance?",                  priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Access Control",                  text: "Is access to financial systems restricted to authorised staff on a need-to-know basis?",                      priority: "Critical", tags: "DPDPA,Technical" },
    { cat: "Access Control",                  text: "Do you conduct periodic access reviews for financial systems to remove stale user accounts?",                  priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Data Security",                   text: "Is customer financial data encrypted both at rest and in transit?",                                            priority: "Critical", tags: "DPDPA,Technical" },
    { cat: "Data Security",                   text: "Do you maintain tamper-evident audit trails for all financial transactions and data access events?",            priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Data Security",                   text: "Do you have controls to prevent and detect insider threats or fraud related to financial data access?",         priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Compliance & Retention",          text: "Do you have data retention policies for financial records that comply with applicable tax and regulatory requirements?", priority: "High", tags: "DPDPA,Legal" },
    { cat: "Compliance & Retention",          text: "Are payment card data processes (if applicable) in scope for PCI-DSS compliance?",                             priority: "High",   tags: "PCI-DSS,Technical" },
    { cat: "Vendor & Third-Party",            text: "Are third-party finance vendors assessed for security and covered by DPAs?",                                   priority: "High",   tags: "DPDPA,Legal" },
    { cat: "Vendor & Third-Party",            text: "Is customer financial data shared with third parties only under contractual data protection obligations?",      priority: "High",   tags: "DPDPA,Legal" },
    { cat: "Incident Response",               text: "Do you have a process for detecting and reporting financial data breaches within regulatory timeframes?",        priority: "Critical", tags: "DPDPA,Organisational" },
    { cat: "Training & Awareness",            text: "Are Finance staff trained on data privacy obligations and phishing risks targeting financial data?",             priority: "Medium", tags: "DPDPA,Organisational" },
  ],
  Legal: [
    { cat: "Data Classification",       text: "Do you identify and classify personal data contained in contracts, legal filings, and correspondence?",              priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Data Classification",       text: "Are privileged and confidential legal documents stored in access-controlled repositories with audit logs?",           priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Data Subject Rights",       text: "Do you have a procedure for responding to Data Subject Access Requests involving Legal department records?",           priority: "High",   tags: "DPDPA,GDPR,Organisational" },
    { cat: "Data Subject Rights",       text: "Is personal data in court filings and regulatory submissions minimised where possible?",                             priority: "Medium", tags: "DPDPA,Legal" },
    { cat: "Legal Hold & Retention",    text: "Do you have a legal hold process that preserves relevant data while preventing indefinite retention of personal data?", priority: "High", tags: "DPDPA,Legal" },
    { cat: "Legal Hold & Retention",    text: "Are retention schedules defined for legal records containing personal data, with secure disposal on expiry?",         priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Vendor & Third-Party",      text: "Are legal software tools (document management, e-discovery) covered by Data Processing Agreements?",                 priority: "High",   tags: "DPDPA,Legal" },
    { cat: "Vendor & Third-Party",      text: "Do external counsel and litigation support vendors comply with your data protection standards under contract?",        priority: "High",   tags: "DPDPA,Legal" },
    { cat: "Cross-Border Transfers",    text: "Do you manage personal data flows across jurisdictions when handling cross-border legal matters?",                    priority: "Medium", tags: "DPDPA,GDPR,Legal" },
    { cat: "Contract Governance",       text: "Do you review contracts with third parties to ensure adequate data protection and confidentiality clauses are included?", priority: "High", tags: "DPDPA,Legal" },
  ],
  Operations: [
    { cat: "Data Inventory",        text: "Do you maintain a data inventory of personal data flowing through operational processes?",                                priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Data Minimisation",     text: "Do you apply data minimisation principles — collecting only the personal data strictly necessary for operational processes?", priority: "Medium", tags: "DPDPA,Organisational" },
    { cat: "Access Control",        text: "Are access rights to operational systems granted on a least-privilege, need-to-know basis?",                             priority: "High",   tags: "DPDPA,Technical" },
    { cat: "System Security",       text: "Are operational data systems (including IoT and edge devices) regularly patched and vulnerability-assessed?",              priority: "High",   tags: "DPDPA,Technical" },
    { cat: "System Security",       text: "Is customer-facing data in operational systems protected with appropriate access controls?",                              priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Vendor & Third-Party",  text: "Do you have data processing agreements with supply chain partners and logistics providers who handle personal data?",      priority: "High",   tags: "DPDPA,Legal" },
    { cat: "Vendor & Third-Party",  text: "Are third-party operational tools and integrations assessed for security before onboarding?",                            priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Incident Response",     text: "Do you have a process for reporting and responding to operational data incidents?",                                       priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Data Retention",        text: "Are defined retention periods in place for operational records containing personal data?",                                priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Training & Awareness",  text: "Are operational staff trained to recognise and report data privacy incidents?",                                          priority: "Medium", tags: "DPDPA,Organisational" },
  ],
  Marketing: [
    { cat: "Consent & Opt-in",       text: "Do you obtain explicit, freely given consent before sending marketing emails, SMS, or push notifications?",              priority: "Critical", tags: "DPDPA,GDPR,Legal" },
    { cat: "Consent & Opt-in",       text: "Do you maintain a suppression list and honour opt-outs promptly?",                                                       priority: "High",   tags: "DPDPA,GDPR,Organisational" },
    { cat: "Consent & Opt-in",       text: "Are website cookies disclosed in a cookie banner, with consent captured before non-essential cookies are set?",          priority: "High",   tags: "GDPR,Legal" },
    { cat: "CRM Data Governance",    text: "Do you have a CRM data governance policy covering how customer records are created, updated, and deleted?",               priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "CRM Data Governance",    text: "Do you regularly audit your marketing database to remove invalid, stale, or unsubscribed contacts?",                     priority: "Medium", tags: "DPDPA,Organisational" },
    { cat: "CRM Data Governance",    text: "Do you have a process for handling customer requests to access, correct, or erase their marketing data?",                 priority: "High",   tags: "DPDPA,GDPR,Organisational" },
    { cat: "Profiling & Targeting",  text: "Is personal data used for customer segmentation limited to what users have consented to?",                               priority: "High",   tags: "DPDPA,GDPR,Legal" },
    { cat: "Profiling & Targeting",  text: "Do you conduct DPIAs before launching campaigns involving new forms of profiling or behavioural targeting?",              priority: "High",   tags: "DPDPA,GDPR,Organisational" },
    { cat: "Vendor & Third-Party",   text: "Are third-party marketing platforms covered by Data Processing Agreements?",                                             priority: "High",   tags: "DPDPA,Legal" },
    { cat: "Vendor & Third-Party",   text: "Do you review advertising partners' data practices to ensure alignment with your privacy policy and user consent?",       priority: "Medium", tags: "DPDPA,Organisational" },
    { cat: "Cross-Border Transfers", text: "Is cross-border transfer of customer data covered by appropriate transfer mechanisms?",                                   priority: "High",   tags: "DPDPA,GDPR,Legal" },
    { cat: "Training & Awareness",   text: "Are marketing staff trained on anti-spam regulations, cookie consent laws, and data privacy obligations?",                priority: "Medium", tags: "DPDPA,Organisational" },
  ],
};

// For custom/unknown departments, generate generic DPDPA questions.
export function getGenericDeptQuestions(dept) {
  return [
    { cat: "Data Inventory",        text: `Does the ${dept} department maintain an inventory of personal data it collects and processes?`,               priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Lawful Basis",          text: `Has the ${dept} department identified a lawful basis for each category of personal data it processes?`,       priority: "High",   tags: "DPDPA,Legal" },
    { cat: "Data Subject Rights",   text: `Does the ${dept} department have a process to respond to data subject requests (access, correction, deletion)?`, priority: "High", tags: "DPDPA,Organisational" },
    { cat: "Data Minimisation",     text: `Does the ${dept} department collect only the minimum personal data necessary for its activities?`,             priority: "Medium", tags: "DPDPA,Organisational" },
    { cat: "Data Retention",        text: `Does the ${dept} department have defined retention periods and securely dispose of personal data when no longer needed?`, priority: "High", tags: "DPDPA,Organisational" },
    { cat: "Access Control",        text: `Is access to personal data held by the ${dept} department restricted to authorised staff only?`,              priority: "High",   tags: "DPDPA,Technical" },
    { cat: "Vendor & Third-Party",  text: `Does the ${dept} department have data processing agreements with third-party vendors who handle personal data?`, priority: "High",  tags: "DPDPA,Legal" },
    { cat: "Incident Response",     text: `Does the ${dept} department have a process for identifying and reporting data breaches?`,                      priority: "High",   tags: "DPDPA,Organisational" },
    { cat: "Training & Awareness",  text: `Are staff in the ${dept} department trained on data privacy obligations relevant to their role?`,              priority: "Medium", tags: "DPDPA,Organisational" },
    { cat: "Data Security",         text: `Is personal data handled by the ${dept} department protected with appropriate technical and organisational security measures?`, priority: "High", tags: "DPDPA,Technical" },
  ];
}
