export const TECH_CATEGORIES = [
  { id: "iam",                      label: "Identity and Access Management (IAM)", placeholder: "e.g. Okta, Azure AD, AWS IAM" },
  { id: "endpoint_protection",      label: "Endpoint Protection",                  placeholder: "e.g. CrowdStrike, SentinelOne, Defender" },
  { id: "email_security",           label: "Email Security",                       placeholder: "e.g. Proofpoint, Mimecast, Google Workspace" },
  { id: "siem",                     label: "SIEM",                                 placeholder: "e.g. Splunk, Microsoft Sentinel, IBM QRadar" },
  { id: "xdr_edr",                  label: "XDR/EDR",                              placeholder: "e.g. CrowdStrike XDR, Palo Alto XDR" },
  { id: "firewalls",                label: "Firewalls",                            placeholder: "e.g. Palo Alto, Fortinet, Cisco ASA" },
  { id: "backup_dr",                label: "Backup & Disaster Recovery",           placeholder: "e.g. Veeam, Commvault, AWS Backup" },
  { id: "vulnerability_management", label: "Vulnerability Management",             placeholder: "e.g. Tenable, Qualys, Rapid7" },
  { id: "dlp",                      label: "DLP",                                  placeholder: "e.g. Symantec DLP, Microsoft Purview" },
  { id: "mdm",                      label: "MDM",                                  placeholder: "e.g. Jamf, Intune, Workspace ONE" },
  { id: "cloud_security",           label: "Cloud Security",                       placeholder: "e.g. AWS Security Hub, Azure Defender" },
  { id: "cspm_cnapp",               label: "CSPM/CNAPP",                           placeholder: "e.g. Wiz, Prisma Cloud, Orca" },
  { id: "pam",                      label: "PAM",                                  placeholder: "e.g. CyberArk, BeyondTrust, Delinea" },
  { id: "casb",                     label: "CASB",                                 placeholder: "e.g. Netskope, Microsoft Defender for Cloud Apps" },
  { id: "waf",                      label: "WAF",                                  placeholder: "e.g. Cloudflare WAF, AWS WAF, Imperva" },
  { id: "api_security",             label: "API Security",                         placeholder: "e.g. Salt Security, Noname, Traceable" },
  { id: "asset_management",         label: "Asset Management",                     placeholder: "e.g. ServiceNow ITAM, Lansweeper, Snipe-IT" },
  { id: "itsm",                     label: "ITSM",                                 placeholder: "e.g. ServiceNow, Jira Service Mgmt, Freshservice" },
  { id: "hrms",                     label: "HRMS",                                 placeholder: "e.g. Workday, BambooHR, SAP SuccessFactors" },
  { id: "erp",                      label: "ERP",                                  placeholder: "e.g. SAP, Oracle ERP, Microsoft Dynamics" },
  { id: "crm",                      label: "CRM",                                  placeholder: "e.g. Salesforce, HubSpot, Dynamics CRM" },
];
