import zlib from "zlib";
import { describe, test, expect } from "vitest";
import { renderFindingEvidencePdf } from "../utils/findingEvidencePdf.js";
import { buildEvidencePayload } from "../connectors/shared/evidencePayload.js";

// pdfkit's output uses FlateDecode-compressed content streams, and this repo's
// pdf-parse version is incompatible with pdfkit 0.15's PDF structure (fails with
// "bad XRef entry" even on pre-existing, unmodified payloads — unrelated to this
// change). To assert on the *rendered text* of a generated PDF without relying on
// that broken combination, inflate every FlateDecode stream in the raw PDF bytes
// and pull out the actual glyph bytes: pdfkit writes each Tj/TJ string operand as
// a hex string (`<...>`) whose bytes are plain WinAnsi/ASCII for the fonts used
// here, so hex-decoding those substrings reconstructs the rendered text.
function extractDecompressedText(buf) {
  const raw = buf.toString("latin1");
  const streamRe = /stream\r?\n([\s\S]*?)\r?\nendstream/g;
  let match;
  let combined = "";
  while ((match = streamRe.exec(raw))) {
    const streamBytes = Buffer.from(match[1], "latin1");
    let content;
    try {
      content = zlib.inflateSync(streamBytes).toString("latin1");
    } catch {
      continue; // Not a Flate-compressed stream (e.g. a font file) — skip it.
    }
    const hexStringRe = /<([0-9a-fA-F]+)>/g;
    let hexMatch;
    while ((hexMatch = hexStringRe.exec(content))) {
      combined += Buffer.from(hexMatch[1], "hex").toString("latin1");
    }
  }
  return combined;
}

describe("renderFindingEvidencePdf", () => {
  test("produces a valid PDF with every report section", async () => {
    const buf = await renderFindingEvidencePdf({
      title: "S3 buckets block public access",
      testKey: "aws.network.s3_public_access_blocked",
      resourceId: "bucket-1",
      severity: "critical",
      message: "bucket-1 has no public access block configuration",
      evidencePayload: { BlockPublicAcls: false, BlockPublicPolicy: false },
      isoReferences: ["A.8.2.3"],
      connectionName: "Prod AWS",
      integrationKey: "aws",
    });
    expect(Buffer.isBuffer(buf)).toBe(true);
    expect(buf.subarray(0, 5).toString()).toBe("%PDF-");

    const content = extractDecompressedText(buf);
    expect(content).toContain("COMPLIANCE FINDING REPORT");
    expect(content).toContain("FINDING IDENTIFICATION");
    expect(content).toContain("EXECUTIVE RISK SUMMARY");
    expect(content).toContain("WHAT WAS DETECTED");
    expect(content).toContain("DETECTION EVIDENCE");
    expect(content).toContain("WHY IT MATTERS");
    expect(content).toContain("COMPLIANCE IMPACT");
    expect(content).toContain("REMEDIATION");
    expect(content).toContain("Immediate action");
    expect(content).toContain("Recommended target architecture");
    expect(content).toContain("REMEDIATION TRACKING");
    expect(content).toContain("VERIFICATION");
    expect(content).toContain("REMEDIATION EVIDENCE");
    expect(content).toContain("REVIEW & SIGN-OFF");
    expect(content).toContain("Generated by PRISM");
    // Stable finding id + numbered remediation steps
    expect(content).toMatch(/PRISM-F-[0-9A-F]{8}/);
    expect(content).toContain("1.");
    // The finding's own data still renders (in What was detected + Before)
    expect(content).toContain("bucket-1 has no public access block configuration");
  });

  test("expands the single ISO reference into a multi-framework control table", async () => {
    const buf = await renderFindingEvidencePdf({
      title: "Security groups do not expose management ports publicly",
      testKey: "aws.network.security_groups_no_open_ingress",
      resourceId: "sg-0abc123",
      severity: "critical",
      message: "sg-0abc123 allows inbound 22 from 0.0.0.0/0",
      evidencePayload: { groupId: "sg-0abc123" },
      isoReferences: ["A.13.1.1"],
      connectionName: "Prod AWS",
      integrationKey: "aws",
    });
    const content = extractDecompressedText(buf);
    expect(content).toContain("ISO/IEC 27001:2013");
    expect(content).toContain("ISO/IEC 27001:2022");
    expect(content).toContain("GDPR");
    expect(content).toContain("DPDPA 2023");
    expect(content).toContain("not a certified crosswalk");
    // A test-specific remediation playbook (not the generic fallback) is used
    expect(content).toContain("Session Manager");
  });

  test("accepts raw controlMappings rows and DB test metadata", async () => {
    const buf = await renderFindingEvidencePdf({
      title: "RDS instances are not publicly accessible",
      testKey: "aws.rds.publicly_accessible",
      resourceId: "prod-db-1",
      severity: "critical",
      message: "prod-db-1 is publicly accessible",
      evidencePayload: { publiclyAccessible: true },
      controlMappings: [{ framework: "ISO27001", isoReference: "A.13.1.1" }],
      testDescription: "Checks every RDS instance has PubliclyAccessible disabled.",
      remediationGuidance: "Disable public accessibility on the instance.",
      connectionName: "Prod AWS",
      integrationKey: "aws",
    });
    const content = extractDecompressedText(buf);
    expect(content).toContain("Checks every RDS instance has PubliclyAccessible disabled");
    expect(content).toContain("DPDPA 2023");
  });

  test("derives a stable finding id from the identity tuple and honours an explicit status / detection date", async () => {
    const common = {
      title: "NSG open",
      testKey: "azure.network.nsg_no_open_ingress",
      resourceId: "nsg-1",
      severity: "critical",
      message: "nsg-1 allows 22 from *",
      evidencePayload: { nsgName: "nsg-1" },
      isoReferences: ["A.13.1.1"],
      connectionName: "Azure",
      integrationKey: "azure",
      companyId: 20,
      connectionId: 4,
    };
    const a = extractDecompressedText(await renderFindingEvidencePdf(common));
    const b = extractDecompressedText(await renderFindingEvidencePdf(common));
    const idA = a.match(/PRISM-F-[0-9A-F]{8}/)[0];
    const idB = b.match(/PRISM-F-[0-9A-F]{8}/)[0];
    expect(idA).toBe(idB); // stable across runs

    const withStatus = extractDecompressedText(
      await renderFindingEvidencePdf({ ...common, status: "acknowledged", firstDetectedAt: "2026-01-02T00:00:00Z" })
    );
    expect(withStatus).toContain("ACKNOWLEDGED");
    expect(withStatus).toContain("02/01/2026");
  });

  test("handles an empty evidence payload and missing optional fields without throwing", async () => {
    const buf = await renderFindingEvidencePdf({
      title: "t",
      testKey: "k",
      resourceId: "r",
      severity: "low",
      message: null,
      evidencePayload: {},
      isoReferences: [],
      connectionName: null,
      integrationKey: null,
    });
    expect(buf.subarray(0, 5).toString()).toBe("%PDF-");
    const content = extractDecompressedText(buf);
    expect(content).toContain("did not meet the expected configuration");
    expect(content).not.toContain("undefined");
  });

  test("renders resourceType/resourceName/region as labeled fields when the evidence payload uses the standardized shape", async () => {
    const buf = await renderFindingEvidencePdf({
      title: "RDS instances have storage encryption enabled",
      testKey: "aws.rds.storage_encrypted",
      resourceId: "arn:aws:rds:us-east-1:123456789012:db:prod-1",
      severity: "critical",
      message: "prod-1 does not have storage encryption enabled",
      evidencePayload: buildEvidencePayload({
        resourceType: "rds_instance",
        resourceId: "arn:aws:rds:us-east-1:123456789012:db:prod-1",
        resourceName: "prod-1",
        region: "us-east-1",
        details: { storageEncrypted: false },
      }),
      isoReferences: ["A.8.2.3"],
      connectionName: "Prod AWS",
      integrationKey: "aws",
    });
    expect(Buffer.isBuffer(buf)).toBe(true);
    expect(buf.subarray(0, 5).toString()).toBe("%PDF-");

    const content = extractDecompressedText(buf);
    expect(content).toContain("RESOURCE TYPE");
    expect(content).toContain("rds_instance");
    expect(content).toContain("RESOURCE NAME");
    expect(content).toContain("prod-1");
    expect(content).toContain("REGION");
    expect(content).toContain("us-east-1");
  });
});
