"""DPDPA Assessment Questions — maps to actual Digital Personal Data Protection Act obligations."""

from __future__ import annotations

# ─── DPDPA Obligation-Based Assessment Questions ──────────────────────────────
# Each question maps to a specific DPDPA section and PRISM pillar.
# The customer's yes/no/partial answers directly determine readiness scores.

DPDPA_QUESTIONS: list[dict] = [
    # ─── P — Policies & Governance ────────────────────────────────────────
    {
        "id": "P1",
        "pillar": "P",
        "dpdpa_section": "Section 5 — Notice",
        "question": "Do you provide a clear privacy notice to individuals before or at the time of collecting their personal data?",
        "why_it_matters": "DPDPA requires every Data Fiduciary to give notice with purpose of processing, rights of the Data Principal, and how to file complaints.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "P2",
        "pillar": "P",
        "dpdpa_section": "Section 6 — Consent",
        "question": "Do you obtain explicit, informed consent before processing personal data (where consent is the lawful basis)?",
        "why_it_matters": "Consent must be free, specific, informed, unconditional, unambiguous, with clear affirmative action.",
        "options": ["Yes", "Partially", "No", "Not Applicable"],
    },
    {
        "id": "P3",
        "pillar": "P",
        "dpdpa_section": "Section 6(4) — Consent Withdrawal",
        "question": "Can individuals withdraw their consent easily, and do you stop processing their data upon withdrawal?",
        "why_it_matters": "Withdrawal of consent must be as easy as giving consent. Processing must cease upon withdrawal.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "P4",
        "pillar": "P",
        "dpdpa_section": "Section 8(3) — Purpose Limitation",
        "question": "Is personal data used only for the specific purpose it was collected for?",
        "why_it_matters": "Data Fiduciaries must process data only for the purpose communicated to the Data Principal.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "P5",
        "pillar": "P",
        "dpdpa_section": "Section 8(7) — Data Retention & Erasure",
        "question": "Do you have defined retention periods and do you erase personal data when it is no longer needed or when consent is withdrawn?",
        "why_it_matters": "DPDPA mandates erasure when data is no longer necessary for the stated purpose.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "P6",
        "pillar": "P",
        "dpdpa_section": "Section 8(1) — Lawful Purpose",
        "question": "Have you documented the lawful purpose for processing personal data across all departments and tools?",
        "why_it_matters": "Processing must be for a lawful purpose. Documentation is evidence of compliance.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "P7",
        "pillar": "P",
        "dpdpa_section": "Section 10 — Children's Data",
        "question": "If you process children's data (under 18), do you obtain verifiable parental consent and avoid tracking/targeting?",
        "why_it_matters": "Processing children's data requires verifiable consent of parent/guardian. Behavioral tracking is prohibited.",
        "options": ["Yes", "Not Applicable", "No", "Not Sure"],
    },
    # ─── R — Risk & Resiliency ────────────────────────────────────────────
    {
        "id": "R1",
        "pillar": "R",
        "dpdpa_section": "Section 8(5) — Breach Notification",
        "question": "Do you have a process to notify the Data Protection Board and affected individuals in case of a personal data breach?",
        "why_it_matters": "DPDPA mandates breach notification to the Board and each affected Data Principal.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "R2",
        "pillar": "R",
        "dpdpa_section": "Section 8(5) — Breach Detection",
        "question": "Do you have mechanisms to detect personal data breaches (unauthorized access, loss, destruction, alteration)?",
        "why_it_matters": "You cannot notify what you cannot detect. Detection capability is foundational to breach response.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "R3",
        "pillar": "R",
        "dpdpa_section": "Section 8(4) — Reasonable Security",
        "question": "Have you implemented reasonable security safeguards to prevent personal data breaches?",
        "why_it_matters": "DPDPA requires 'reasonable security safeguards' to protect personal data from breach.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "R4",
        "pillar": "R",
        "dpdpa_section": "Section 8(4) — Vendor Security",
        "question": "Do your Data Processors (vendors handling personal data) have contractual obligations and security measures?",
        "why_it_matters": "Data Fiduciary remains responsible for processors. Contracts must ensure equivalent protection.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    # ─── I — Identity & People ────────────────────────────────────────────
    {
        "id": "I1",
        "pillar": "I",
        "dpdpa_section": "Section 8(2) — Accuracy",
        "question": "Do you ensure personal data is accurate, complete, and up-to-date when it is likely to be used for decisions or shared?",
        "why_it_matters": "Data Fiduciary must ensure completeness, accuracy, and consistency of personal data.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "I2",
        "pillar": "I",
        "dpdpa_section": "Section 11 — Data Principal Rights",
        "question": "Can individuals access their personal data, request correction, and request erasure from your systems?",
        "why_it_matters": "Data Principals have the right to access, correction, erasure, and grievance redressal.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "I3",
        "pillar": "I",
        "dpdpa_section": "Section 11(3) — Grievance Redressal",
        "question": "Do you have a grievance redressal mechanism for individuals to raise complaints about how their data is handled?",
        "why_it_matters": "Every Data Fiduciary must provide a mechanism for Data Principals to register grievances.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "I4",
        "pillar": "I",
        "dpdpa_section": "Section 8 — Awareness & Training",
        "question": "Are employees trained on personal data handling responsibilities and breach reporting procedures?",
        "why_it_matters": "People are the first line of defense. Untrained staff lead to accidental breaches.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    # ─── S — Security Architecture ───────────────────────────────────────
    {
        "id": "S1",
        "pillar": "S",
        "dpdpa_section": "Section 8(4) — Technical Safeguards",
        "question": "Is personal data encrypted at rest and in transit across your systems and tools?",
        "why_it_matters": "Encryption is a fundamental technical safeguard under 'reasonable security'.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "S2",
        "pillar": "S",
        "dpdpa_section": "Section 8(4) — Access Controls",
        "question": "Is access to personal data restricted based on role, with MFA for sensitive systems?",
        "why_it_matters": "Unauthorized access is a breach. Role-based access with MFA prevents it.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "S3",
        "pillar": "S",
        "dpdpa_section": "Section 8(4) — Monitoring",
        "question": "Do you monitor and log access to personal data, with alerts for unusual activity?",
        "why_it_matters": "Logging and monitoring enable breach detection and provide audit evidence.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "S4",
        "pillar": "S",
        "dpdpa_section": "Section 16 — Cross-Border Transfer",
        "question": "If personal data is transferred outside India, is it only to countries/sectors notified by the Central Government?",
        "why_it_matters": "DPDPA restricts cross-border transfer to government-approved jurisdictions only.",
        "options": ["Yes", "Not Applicable", "No", "Not Sure"],
    },
    # ─── M — Management Review & Audit ────────────────────────────────────
    {
        "id": "M1",
        "pillar": "M",
        "dpdpa_section": "Section 8(1) — Accountability",
        "question": "Has your organisation appointed a Data Protection Officer or equivalent role responsible for DPDPA compliance?",
        "why_it_matters": "Significant Data Fiduciaries must appoint a DPO. Others benefit from clear accountability.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "M2",
        "pillar": "M",
        "dpdpa_section": "Section 8 — Periodic Audit",
        "question": "Do you conduct periodic audits of personal data processing activities and compliance controls?",
        "why_it_matters": "Significant Data Fiduciaries must conduct periodic audits. It demonstrates active governance.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "M3",
        "pillar": "M",
        "dpdpa_section": "Section 8 — Records & Evidence",
        "question": "Do you maintain records of data processing activities, consent records, and breach response actions?",
        "why_it_matters": "Records are evidence of compliance. The Data Protection Board may request them.",
        "options": ["Yes", "Partially", "No", "Not Sure"],
    },
    {
        "id": "M4",
        "pillar": "M",
        "dpdpa_section": "Section 8(6) — Significant Data Fiduciary",
        "question": "Have you assessed whether your organisation qualifies as a Significant Data Fiduciary (based on volume/sensitivity of data)?",
        "why_it_matters": "Significant Data Fiduciaries have additional obligations including DPO, DPIA, and periodic audits.",
        "options": ["Yes", "Not Applicable", "No", "Not Sure"],
    },
]
